[package]
name = "paisley-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
colored = "2.1.0"
plex = "0.3.1"
regex = "1.10.6"
structopt = "0.3.26"
