use std::path::PathBuf;
use structopt::StructOpt;

#[derive(Debug, StructOpt)]
#[structopt(
	name = "Paisley Compiler",
	about = "A shell language with consistent syntax and a complete standard library."
)]
pub struct Options {
	/// The input file
	#[structopt(parse(from_os_str))]
	pub input: PathBuf,

	/// Output tokens generated by the lexer
	#[structopt(long)]
	pub output_tokens: bool,

	/// Output AST generated by the parser
	#[structopt(long)]
	pub output_ast: bool,
}

pub fn read() -> Options {
	return Options::from_args();
}
